### ISSUE TITLE
OSCListener not in net.swift?

### ISSUE THREAD

**Issue by jbmaxwell** [segabor/OSCCore#5]
I've just included OSCCore in my package description—tried "majorVersion: 0" and "majorVersion: 0, minor: 2"—but whatever I get checked out doesn't include OSCListener (and obviously doesn't work). I'll try pulling down the files manually, but maybe you have another suggestion?

**Comment by segabor** [comment]
Hi,

It looks like the last tag was bogus. Let me create a new tag 0.2.3 that includes all the latest changes accidentally left out from 0.2.2.

Gábor

**Comment by segabor** [comment]
Release 0.2.3 is out. Please check it out and let me know if it works out.
Thanks,

Gábor

**Comment by jbmaxwell** [comment]
Yes! That's got it work for me. Thanks!

**Comment by segabor** [comment]
Thanks for the feedback!
