### ISSUE TITLE
Give up on Zewo UDP package

### ISSUE THREAD

**Issue by segabor** [segabor/OSCCore#7]
OSC uses UDP package of Zewo for UDP communication. The package has been moved to attic, so we need to find an alternate solution either by finding another package or rewrite the communication layer from scratch.

**Comment by segabor** [comment]
A good candidate https://github.com/IBM-Swift/BlueSocket/

**Comment by segabor** [comment]
Started working on this ticket. Assigned repo: https://github.com/segabor/OSCCore/tree/blue_socket

**Comment by jbmaxwell** [comment]
I've been trying to get OSCCore going in my Swift macOS app, and it's failing on createUDPChannel(localPort:remotePort:). No errors given. Do you know if the version of UDP you're using runs under Xcode 9/Swift 4.0?

**Comment by segabor** [comment]
Hi,

Where do you want to connect? Is remote address localhost? Is it possible that UDP traffic is somehow blocked? Just guessing without details.

I have not tried It with Swift 4 but will be ported later.

PS.: if issue persists feel free to open a new ticket

**Comment by jbmaxwell** [comment]
Hi, yes, I'm trying to connect to localhost, but in my initial look at it I couldn't find a place to specify. I have UDP working within MaxMSP, so it must be open.

**Comment by segabor** [comment]
I can only think that the connection was established but max did not understood the received packets.
I developed the code by experimenting with SuperCollider.
Does max support some kind of debugging like OSC debug panel?
