### ISSUE TITLE
Are there any plans to create a Cocoapods pod for this?

### ISSUE THREAD

**Issue by j0hnm4r5** [segabor/OSCCore#8]
All that's really necessary is to decide on a license for the project.

**Comment by segabor** [comment]
Hi,

No plans yet but PRs are welcome. License will be picked soon.

**Comment by segabor** [comment]
Done.

**Comment by segabor** [comment]
I close this ticket for now. @j0hnm4r5 please let me know if you need Cocoapod support or you want to add it.
